---
- name: Docker | Gather required facts
  ansible.builtin.setup:
    filter: ansible_distribution*

- name: Docker | Install docker on debian-based OS
  ansible.builtin.import_tasks: debian.yaml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
