---
- name: Docker | Install packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: present
    update_cache: true

- name: Docker | Install repo key
  ansible.builtin.apt_key:
    url: "{{ docker_apt_key_url }}"
    state: present

- name: Docker | Add repo
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present

- name: Docker | Install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Docker | Create docker config
  ansible.builtin.copy:
    content: "{{ docker_daemon_opts | to_nice_json }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
  notify: Restart docker
